load("@linux_kernel_headers//:defs.bzl", "linux_kernel_headers")


linux_kernel_headers(
    name="k151",
    kernel_version="4.14.151",
    config=":x86_64.config"
)


linux_kernel_headers(
    name="k159",
    kernel_version="4.14.159",
    config=":x86_64.config"
)



linux_kernel_headers(
    name="k154",
    kernel_version="4.14.154",
    config=":x86_64.config"
)

